# This is a pod w/ restartPolicy=Never so that the installer only runs once.
apiVersion: v1
kind: Pod
metadata:
  name: gestalt-cdk-install
  labels:
    gestalt-app: cdk-install
spec:
  restartPolicy: Never
  containers:
  - name: gestalt-cdk-install
    image: "galacticfog/gestalt-cdk-install:kube-1.1.0"
    imagePullPolicy: Always
    # 'deploy' arg signals deployment of gestalt platform
    args: ["deploy"]
    env:
    - name: CONTAINER_IMAGE_RELEASE_TAG
      value: kube-1.0.0
    # - name: EXTERNAL_GATEWAY_DNSNAME
    #   value: "$GESTALT_EXTERNAL_GATEWAY_DNSNAME"
    # - name: EXTERNAL_GATEWAY_PROTOCOL
    #   value: "$GESTALT_EXTERNAL_GATEWAY_PROTOCOL"
    # - name: KUBECONFIG_DATA
    #   value: "$KUBECONFIG_DATA"
    # - name: GESTALT_INSTALL_MODE
    #   value: "$GESTALT_INSTALL_MODE"
